name: 学习github workflow
on: workflow_dispatch

jobs:
  run-index:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆代码
        run: |
          git clone https://github.com/helloNN/testToStudy.git
          pwd
          tree

      - name: 运行node.js
        run: |
          cd testToStudy
          pwd
          tree
          npm start
