name: 学习github workflow
on: workflow_dispatch

jobs:
  run-index:
    runs-on: ubuntu-latest
    steps:
      - name: 显示当前地址
        run: pwd

      - name: 显示目录文件
        run: |
          pwd
          ls `pwd`
          ls `pwd`/..

      - name: 运行linux命令
        run: |
          echo hello world > hello.txt
          date
